openapi: 3.0.3
info:
    title: Karlis API
    version: '713.33'
    description: YAOA
    termsOfService: OKAY
    contact:
        email: email@email.com
        name: Youza
        url: www.example.com/contact
    license:
        name: MIT 2.0
        url: www.example.com/license
servers:
    - url: http://localhost:3000/
      variables: {}
      description: Local server
    - url: https://my-json-server.typicode.com/CurtisLV/API_workshop_23.05.2023./api
      variables: {}
      description: My db.json
    - url: fake github server
      variables: {}
      description: https://my-json-server.typicode.com/bearc0025/api
paths:
    /users:
        summary: user operations for fetching an creating new users
        description: fetch and store
        get:
            summary: fetch users from server
            description: returns users
            operationId: fetchUsers
            responses:
                '200':
                    description: success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FullUser'
                default:
                    description: Default error sample response
            tags:
                - Users
        post:
            summary: create user
            description: store user on a server
            operationId: createUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                    example: Karlis
                                score:
                                    type: integer
                                    example: 33
                                active:
                                    type: boolean
                                    example: true
                            required:
                                - username
            responses:
                '201':
                    description: success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FullUser'
                default:
                    description: Default error sample response
            tags:
                - Users
components:
    schemas:
        FullUser:
            type: object
            properties:
                id:
                    type: string
                    example: 1234abc
                username:
                    type: string
                    example: bearc
                score:
                    type: integer
                    example: 55
                active:
                    type: boolean
                    example: true
